### ISSUE TITLE
强行停止支付宝，再打开支付宝，配置会恢复默认配置

### ISSUE THREAD

**Issue by oneplusa5000** [pansong291/XQuickEnergy#10]
如题，在文件里面修改配置后，打开支付宝，支付宝会按照修改后的配置运行，强行停止支付宝或支付宝被杀死后，再次打开支付宝，之前修改的配置会变成原始的默认配置。

**Comment by pansong291** [comment]
没有出现该问题，请提供模块管理器中的模块日志。
如果是EdXposed Manager，则模块日志路径为
```
/data/user_de/0/org.meowcat.edxposed.manager/log/error.log
```
如果是Xposed Installer或者EdXposed Installer，模块路径请自行百度

**Comment by oneplusa5000** [comment]
[xposed_error_20190804_153452.log](https://github.com/pansong291/XQuickEnergy/files/3464670/xposed_error_20190804_153452.log)
日志文件

**Comment by pansong291** [comment]
你的配置文件填写错误：
```
"waterFriendList": [
     20887224051****0
     20880221478****1
],
```
两个用户id之间请用英文逗号隔开。

**Comment by 3508454055** [comment]
欢迎进QQ辅助群交流：323175670
