### ISSUE TITLE
庄园自动答题失效

### ISSUE THREAD

**Issue by tpnet** [pansong291/XQuickEnergy#100]
看了日志，找不到正确答案了，没有自动答题了。

这是今天凌晨的日志
![image](https://user-images.githubusercontent.com/17380722/71411498-75ac8300-2684-11ea-88cd-e14c21911d61.png)

**Comment by tpnet** [comment]
我丢，这日志是12月6号的，不知道是不是这个日志

**Comment by louzhushige** [comment]
> 看了日志，找不到正确答案了，没有自动答题了。
> 
> 这是今天凌晨的日志
> ![image](https://user-images.githubusercontent.com/17380722/71411498-75ac8300-2684-11ea-88cd-e14c21911d61.png)

正常，不一定每次都答对。农场里面有个运动会，进去玩也可以领饲料。作者要是能把自动玩运动会游戏加进来就厉害了😂。

**Comment by ggxxuser** [comment]
答题本来就是调用的第三方接口，第三方没有正确答案，XQE当然也是答不出来的。

**Comment by tpnet** [comment]
好的，close 了

**Comment by 3508454055** [comment]
欢迎进QQ辅助群交流：323175670
