### ISSUE TITLE
请求支持息屏收取

### ISSUE THREAD

**Issue by zhuxf8** [pansong291/XQuickEnergy#11]
息屏收取太需要了，老是要进入森林和庄园界面才能触发自动收取。还有消息展示请求支持关闭选项。只要模块能正常，关闭消息展示能无感知收取也蛮好的。

**Comment by magicwaltzlzy** [comment]
息屏收取必须支付宝常驻后台，会很费电吧。目前可以用手动修改配置文件关闭通知，如果作者能抽空搞个用户界面，加入选项，确实会更方便些。

**Comment by zhuxf8** [comment]
目前是两种消息通知，希望还出个配置可以关闭消息通知

**Comment by pansong291** [comment]
熄屏收取暂时无望。个人觉得Toast应该不会有什么影响，无焦点，而且1秒多点就自动消失，跟无通知基本一样。

**Comment by abcdol** [comment]
早就支持息屏收取了 自己用edge手动依次触发运动-森林-庄园即可

**Comment by muyiyl** [comment]
@abcdol 请问具体操作如何

**Comment by 3508454055** [comment]
欢迎进QQ辅助群交流：323175670
