### ISSUE TITLE
在太极环境下无法激活

### ISSUE THREAD

**Issue by anye1998** [pansong291/XQuickEnergy#14]
v1.1.0版本在太极环境下无法激活，v1.0.7-alpha.5、v1.0.7-alpha.4可以正常使用。在v1.1.0版本下，尝试过重启，重复勾选，卸载重新安装都不可以，经查看，目录下面也没有配置文件。
环境：太极 安卓8.0
如果需要日志的话请告诉我位置，我会帮忙抓取。

希望能够修复，谢谢啦！

**Comment by Nifury** [comment]
同样的问题，不过我是在10.1.70下测试的，不知道是不支持高版本还是没有激活

**Comment by anye1998** [comment]
> 
> 
> 同样的问题，不过我是在10.1.70下测试的，不知道是不支持高版本还是没有激活

@Nifury  我都是10.1.70，v1.0.7-alpha.5、v1.0.7-alpha.4都可以激活使用，就v1.1.0无法激活，这就很费解。

**Comment by jihuoma** [comment]
> v1.1.0版本在太极环境下无法激活，v1.0.7-alpha.5、v1.0.7-alpha.4可以正常使用。在v1.1.0版本下，尝试过重启，重复勾选，卸载重新安装都不可以，经查看，目录下面也没有配置文件。
> 环境：太极 安卓8.0
> 如果需要日志的话请告诉我位置，我会帮忙抓取。
> 
> 希望能够修复，谢谢啦！

请教一下，太极里面如何安装支付宝呢？谢谢

**Comment by anye1998** [comment]
> 
> 请教一下，太极里面如何安装支付宝呢？谢谢
@jihuoma 我是太极阳，支付宝正常安装，然后添加到太极就好了

**Comment by jihuoma** [comment]
> > 请教一下，太极里面如何安装支付宝呢？谢谢
> 
> @jihuoma 我是太极阳，支付宝正常安装，然后添加到太极就好了

谢谢你。我没root，嘿嘿。

**Comment by anye1998** [comment]
> 
> 谢谢你。我没root，嘿嘿。

@jihuoma 太极阴可以免root使用，方法官网有https://taichi.cool/README_CN.html

**Comment by dilexis** [comment]
相同的问题，1.0.7的几个测试版本都能正常使用，但是1.1.0就用不了。
尝试了好几次最终退回Alpha5了...
支付宝版本10.1.70，手机一加7 Pro

**Comment by pansong291** [comment]
不好意思，110版本给你们带来困扰，由于太极的模块保护机制导致太极不支持该版本，下次更新就没问题了。

**Comment by Nifury** [comment]
感谢更新！但是现在太极只支持到1.1.0，现在只要等待太极更新支持1.1.1就行了是吗？

**Comment by pansong291** [comment]
@Nifury 由于我并不是使用的太极，所以我目前也无法得知具体进展

**Comment by anye1998** [comment]
@pansong291 感谢大佬，现在太极也支持v1.1.1-alpha.1了，使用没问题，感谢感谢！

**Comment by 3508454055** [comment]
欢迎进QQ辅助群交流：323175670
