### ISSUE TITLE
1.1.2版bug反馈

### ISSUE THREAD

**Issue by dozen007** [pansong291/XQuickEnergy#15]
支付宝版本10.1.70.8308
xquickenergy版本1.1.2

蚂蚁森林：开始领取任务奖励，卡住，没有反应，退出再进还是一样
蚂蚁庄园：开始领取道具，卡住，没有反应，退出再进还是一样

现在xquickenergy退回1.1.1-1，一切正常

**Comment by pansong291** [comment]
你好请提供模块日志。文件路径见下：
Xposed Installer：
```
/data/user_de/0/de.robv.android.xposed.installer/log/
```
EdXposed Installer：
```
/data/user_de/0/com.solohsu.android.edxp.manager/log/
```
EdXposed Manager：
```
/data/user_de/0/org.meowcat.edxposed.manager/log/
```

**Comment by dozen007** [comment]
http://mail.qq.com/cgi-bin/ftnExs_download?k=cc9a3930dc90fc08fee94d303363656333d2703031636563164a05535750010201544e515055044e07515b561c5a5d0005485b550953015a5257530603016c635617115f434d090c547170dd947fa3e9f1a83e8f95fad37becc1f9cbd6c9&t=exs_ftn_download&code=3ec01cec&from=mobile&expiretime=-1&fsize=1.23M&suffix=log&func=3

**Comment by pansong291** [comment]
根据你提供的日志来看，并没有出现你所说的异常情况。若确实有该情况发生，请先在Xposed Installer中清理掉日志，再打开森林庄园复现该异常情况，再上传模块日志。
P.S. github的issues自带上传文件功能。

**Comment by dozen007** [comment]
上传的日志应该是1.1.1-1的日志
