### ISSUE TITLE
只显示开始收取，但是实际上却没有收取

### ISSUE THREAD

**Issue by Exrealaz** [pansong291/XQuickEnergy#16]
如题，支付宝版本10.1.68.7434，xqe版本1.1.2，日志里面也只显示进入我的森林和我自己收取别人的

**Comment by pansong291** [comment]
你是安卓7是吧，该bug已经发现，等待更新即可，或者先使用1.1.1-alpha.1版本。

**Comment by Exrealaz** [comment]
大佬666

**Comment by 3508454055** [comment]
欢迎进QQ辅助群交流：323175670
