### ISSUE TITLE
支付宝疑似热更新，插件失效

### ISSUE THREAD

**Issue by anye1998** [pansong291/XQuickEnergy#20]
支付宝疑似热更新，插件失效，我使用的是10.1.72.7000，酷安评论区也有人反映插件失效。

**Comment by hao1196561270** [comment]
顶

**Comment by pansong291** [comment]
据说8月28号20点开始大批森林辅助类模块失效，当天晚上我也验证了确实失效了，不过我什么都没做，第二天中午又正常了

**Comment by yingang2** [comment]
并不能用啊

**Comment by pansong291** [comment]
> 并不能用啊

@yingang2 难道就我一个人的支付宝10.1.72.7000版本恢复正常？

**Comment by anye1998** [comment]
@pansong291 我也不能用，能用的话我早就把问题关了。。。

**Comment by boomsharklak** [comment]
间歇性的…今天一早可以用，后来在进去又不能用了，很神奇…

**Comment by hao1196561270** [comment]
又不能用了

**Comment by xu-liyan** [comment]
XQuickEnergy1.1.0，支付宝10.1.68.7434，天天都在用，稳稳的，没有失效过。

**Comment by anye1998** [comment]
最新版，把支付宝数据清除，问题解决，此issue关闭

**Comment by anye1998** [comment]
我太难了，就起效了几分钟，又不行了

**Comment by pansong291** [comment]
> 我太难了，就起效了几分钟，又不行了

。。。。。。

**Comment by anye1998** [comment]
> 
> 
> > 我太难了，就起效了几分钟，又不行了
> 
> 。。。。。。

请问在哪里可以抓取日志，我是可以带着日志来反馈的。。。 @pansong291

**Comment by pansong291** [comment]
> 请问在哪里可以抓取日志，我是可以带着日志来反馈的。。。 @pansong291
@anye1998 这个是hook函数变更，日志是没有的

**Comment by anye1998** [comment]
> 
> 
> > 请问在哪里可以抓取日志，我是可以带着日志来反馈的。。。 @pansong291
> 
> @anye1998 这个是hook函数变更，日志是没有的

这就很难受了，没法复现就没法修复，那只能等支付宝更新了，然后看看插件跟进更新能不能解决

**Comment by yingang2** [comment]
清除缓存 能用1次 第2次就不能用了  反复试也是  有跟我一样的吗

**Comment by boomsharklak** [comment]
@yingang2 我也是，已经装回旧版了，旧版一点问题没，原因不明，玄学

**Comment by leyan22** [comment]
我和楼上的一样，每次清除数据后第一次能用，第二次再进支付宝就没反应了

**Comment by leyan22** [comment]
刚才又测试了一下，play版72.6315可用！国内版72.7000只有第一次有效，退出后再进就失效了

**Comment by anye1998** [comment]
最新版支付宝，使用了几天没问题，关闭此issue

**Comment by imdingtalk** [comment]
热更新，手机厂商和应用市场得同意才行吧

**Comment by 3508454055** [comment]
欢迎进QQ辅助群交流：323175670
