### ISSUE TITLE
此刻我有一个大胆的想法

### ISSUE THREAD

**Issue by abcdol** [pansong291/XQuickEnergy#23]
关于息屏偷取和后台偷取，其实说到底应该就是触发器的问题吧？现在应该是进入蚂蚁森林作为偷能量的触发器，进入蚂蚁庄园作为赶鸡的触发器，很显然这俩都是被动的。
息屏偷取和后台偷取能不能加一个主动的触发方式呢，或者是意图，或者是活动，类似于蚂蚁森林的启动意图这种，这样就可以通过edge或者tasker直接调用实现主动的偷能量了吧，只要这个意图没有界面，支付宝在后台，完全可以通过edge定时调用实现定时和循环偷取的吧😂
其实我也不是很明白，就是隐隐约约有点想法，大佬看看这种思路呗，如果能给一个主动触发偷能量的意图很多事情就简单很多了😂

**Comment by kai648846760** [comment]
对于ROOT 用户来说   很好实现  直接用xposed edg pro/ taker实现就可以了    添加多重动作，定时计划。。。
对于非ROOT用户，无法执行shell命令，模拟手动点击虽然可以实现，体验很差，建议能做个后台的触发器。类似于间隔刷新的，设置一个刷新间隔，然后实时捕获森林、庄园、积分的状态。。

**Comment by abcdol** [comment]
我的意思你没看懂。现在软件必须进入森林和庄园界面才能被激活，软件内不提供接口你不可能实现后台静默收取的，重点是静默。另外，tasker。

**Comment by 3508454055** [comment]
欢迎进QQ辅助群交流：323175670
