### ISSUE TITLE
 XQE1.1.6运行不了 打开就是闪退停止运行

### ISSUE THREAD

**Issue by hujia4589** [pansong291/XQuickEnergy#26]
要求提供的反馈的文件提取不到  
在魅族2 手机中  XPOSED的版本是V89    XQE1.1.6运行不了 打开就是闪退停止运行。在酷安上也有多人提出闪退，停止运行。请修复喔。
在安卓模拟器中 同样是 XPOSED的版本是V89    XQE1.1.6运行不了 打开就是闪退停止运行。

另外在小米手机上的EXPOSED还未适配1.1.6，想办法适配一下喔。

**Comment by abcdol** [comment]
edxp还需要适配？

**Comment by abcdol** [comment]
没有日志咋修复

**Comment by abcdol** [comment]
先自己想办法得到日志吧

**Comment by hujia4589** [comment]
说错了  是太极还没有适配

**Comment by pansong291** [comment]
只有魅族手机才会闪退吗？不清楚什么原因

**Comment by pansong291** [comment]
方便的话加一下我QQ1908701778，需要测试一下

**Comment by hujia4589** [comment]
模拟器下也是闪退    我用的逍遥   之前一直都是没问题。   魅族2  1.1.6反正闪退  没有日志  而且勾选记录log  就收不了能量。  小米用exposed 暂时没问题。

**Comment by hujia4589** [comment]
加你好友了  具体可以细聊

**Comment by pansong291** [comment]
> 加你好友了 具体可以细聊

已通过，不知道你是哪一位

**Comment by llsl666** [comment]
我也有问题，已经激活，但是到了森林没反应  无对话，但是每次打开支付宝都有提示打开森林的提醒

**Comment by hujia4589** [comment]
老大已经修复   下新版本

**Comment by llsl666** [comment]
我说的就是1.20新版本啊

**Comment by llsl666** [comment]
难道是我支付宝版本问题？72.7000

**Comment by pansong291** [comment]
> 我说的就是1.20新版本啊

@llsl666 v1.2.1版本已修复该问题

**Comment by abcdol** [comment]
你用了别的软件 xqe打开支付宝没有提示

**Comment by abcdol** [comment]
你是不是还用了庄园 xqe打开支付宝是没有提示的

**Comment by llsl666** [comment]
我没有用庄园，我打开了支付宝xquick有提示我打开支付宝，但是我开了庄园他，没有反应，用的edxp  最新的4470  这两天更新的   xquick也没有显示未激活，就是很奇怪，就是不工作  还是他要开后台弹出界面这类的权限  miui系统最新开放

**Comment by llsl666** [comment]
安装1.21也是没反应，只是开了支付宝，通知栏有提示

**Comment by llsl666** [comment]
还是说是我现在没领的没起作用，等得好友有新的能量才起作用

**Comment by 3508454055** [comment]
欢迎进QQ辅助群交流：323175670
