### ISSUE TITLE
使用对话框, 支付宝提示闪退

### ISSUE THREAD

**Issue by RogenCN** [pansong291/XQuickEnergy#28]
版本信息: 支付宝10.68, 太极阳, MIUI10(9.0) ,
用对话框后台运行时, 支付宝会闪退, 改用toast气泡, 则不会提示闪退. 
只是比较喜欢对话框, 并不影响使用.
另外, 希望-小鸡也能像森林一样可以后台运行, 还有日志保存1天能自动清除, 感谢作者!

**Comment by abcdol** [comment]
rm -rf /storage/emulated/0/Android/data/pansong291.xposed.quickenergy/energy.log

**Comment by abcdol** [comment]
edge里设置成每天一次

**Comment by RogenCN** [comment]
[](url)

**Comment by RogenCN** [comment]
哪里上传附件?

**Comment by pansong291** [comment]
![点击查看图片](https://github.com/pansong291/Pictures/raw/master/github/pansong291/XQuickEnergy/github_issues_upload_files.jpg)  
没有啊，你自己设置了什么定时任务还是其他森林辅助模块在工作？

**Comment by abcdol** [comment]
这个是因为你把自己加入了喂鸡名单 最新版已经修复 关闭了吧

**Comment by 3508454055** [comment]
欢迎进QQ辅助群交流：323175670
