### ISSUE TITLE
打开支付宝蚂蚁森林闪退

### ISSUE THREAD

**Issue by oneplusa5000** [pansong291/XQuickEnergy#29]
手机型号版本:一加五
安卓版本:8.1
XQE版本:1.16
支付宝版本:10.1.68

在1.14版本时正常，升级到1.16版本时，打开支付宝蚂蚁森林时闪退，使用蚂蚁庄园正常。
支付宝转换成了系统软件

[xposed_error_20190919_111929.log](https://github.com/pansong291/XQuickEnergy/files/3629241/xposed_error_20190919_111929.log)
[xposed_error_20190919_111929.log](https://github.com/pansong291/XQuickEnergy/files/3629242/xposed_error_20190919_111929.log)

**Comment by pansong291** [comment]
你好，根据你提供的日志，可以知道森林功能无故被中途截止，但并没有异常发生。

**Comment by oneplusa5000** [comment]
好的，谢谢了，我找到原因了
小鸡炖蘑菇可能和这个软件有冲突
卸载小鸡炖蘑菇就好了

**Comment by 3508454055** [comment]
欢迎进QQ辅助群交流：323175670
