### ISSUE TITLE
建议增加延时偷取

### ISSUE THREAD

**Issue by Jsonylq** [pansong291/XQuickEnergy#32]
对于后台自动偷取，建议增加延时偷取好友能量，天天秒偷容易伤人心，会被记仇的😅

**Comment by pansong291** [comment]
先更新版本，如果不想秒偷，请将检测间隔设置大一些，如5分钟、8分钟，提前时间设置大一些，如1500毫秒、2000毫秒，收取间隔设置大于收取超时，如1500毫秒，收取超时设置小于收取间隔，如1秒。

**Comment by 3508454055** [comment]
欢迎进QQ辅助群交流：323175670
