### ISSUE TITLE
1.2.2可以偷，1.2.3反而不行了

### ISSUE THREAD

**Issue by kleveralt** [pansong291/XQuickEnergy#33]
太极magisk，支付宝75
[runtime.log](https://github.com/pansong291/XQuickEnergy/files/3655331/runtime.log)

**Comment by Rakau** [comment]
使用EDXPOSED试试

**Comment by pansong291** [comment]
根据日志内容来看，你的xposed环境有问题，新的模块未完全正常运行

**Comment by kleveralt** [comment]
嗯确实 太极的引擎还没有适配1.2.3

**Comment by 3508454055** [comment]
欢迎进QQ辅助群交流：323175670
