### ISSUE TITLE
展示模式如何改成toast气泡模式？

### ISSUE THREAD

**Issue by Avwqs** [pansong291/XQuickEnergy#5]
我在Android/data/pansong291.xposed.quickenergy 
配置文件：配置文件目录/config.json 里面添加了代码"showMode":"toast",，但是展示模式没有改变
![Screenshot_2019-07-17-13-37-44-558_bin mt plus](https://user-images.githubusercontent.com/32660279/61349834-16a63f00-a898-11e9-9414-03fc2e04484b.png)

**Comment by pansong291** [comment]
1.0.6版本才支持该功能。

**Comment by ruilijun** [comment]
希望作者能加入打赏功能，比较喜欢你的软件，还有能添加定时的吗？望采纳，谢谢！😋

**Comment by 3508454055** [comment]
欢迎进QQ辅助群交流：323175670
