### ISSUE TITLE
1.2.6似乎是英文了。。

### ISSUE THREAD

**Issue by zhangguanzhang** [pansong291/XQuickEnergy#56]
[请先阅读此反馈 BUG 的注意事项，再提交](https://github.com/pansong291/XQuickEnergy/issues/25)
我安装了好像是英文，没找到哪里切换语言的，还是说是i18n的原因，我网络处于国外

**Comment by zhangguanzhang** [comment]
好吧- -，看了下源码里面菜单就是故意英文的

**Comment by yjr815jun** [comment]
为什么故意英文？英文不好好难受

**Comment by zhangguanzhang** [comment]
开发者为了提高使用门槛，也就是只希望给圈内的玩机人士使用，从而避免出现app出现被盗卖的现象，

**Comment by yjr815jun** [comment]
我不倒卖也不盗卖...宁愿出什么付费下载中文版...这样的门槛确定算门槛么？也不知道防滥用还是看不起中文不好的朋友...

**Comment by pansong291** [comment]
@yjr815jun 并不是为了防盗卖，一个免费还开源的东西你觉得还要防止盗卖吗？那为何不做成闭源收费的？也并不是看不起中文不好的人，除非有的人自己心里自卑才会这么想了。软件主界面写了一句话，就是原因。

**Comment by 3508454055** [comment]
欢迎进QQ辅助群交流：323175670

**Comment by 3508454055** [comment]
> 我不倒卖也不盗卖...宁愿出什么付费下载中文版...这样的门槛确定算门槛么？也不知道防滥用还是看不起中文不好的朋友...

欢迎进QQ辅助群交流：323175670
