### ISSUE TITLE
在EdXposed中勾选后重启，打开蚂蚁森林无反应！多次尝试依然。是否合适Edxposed。

### ISSUE THREAD

**Issue by oliegsan** [pansong291/XQuickEnergy#6]
![Screenshot_2019-07-20-21-51-15-392_com solohsu android edxp manager](https://user-images.githubusercontent.com/49189754/61579526-b255da80-ab38-11e9-9c16-76b66209f7b4.png)

**Comment by pansong291** [comment]
请提供EdXposed Installer的模块日志。绝对路径是/data/user_de/0/com.solohsu.android.edxp.manager/log/error.log

**Comment by oliegsan** [comment]
> 请提供EdXposed Installer的模块日志。绝对路径是/data/user_de/0/com.solohsu.android.edxp.manager/log/error.log



> 请提供EdXposed Installer的模块日志。绝对路径是/data/user_de/0/com.solohsu.android.edxp.manager/log/error.log


> 请提供EdXposed Installer的模块日志。绝对路径是/data/user_de/0/com.solohsu.android.edxp.manager/log/error.log

[error.log](https://github.com/pansong291/XQuickEnergy/files/3413808/error.log)

**Comment by oliegsan** [comment]
> 请提供EdXposed Installer的模块日志。绝对路径是/data/user_de/0/com.solohsu.android.edxp.manager/log/error.log

[error.log](https://github.com/pansong291/XQuickEnergy/files/3413813/error.log)

**Comment by pansong291** [comment]
这个日志的数据有点少，无法得知具体原因，若你愿帮助我改进，请在酷安上私信我你的联系方式（QQ号），我需要进一步进行测试。

**Comment by ruilijun** [comment]
希望作者添加打赏功能，我想支持你，还有能添加定时功能就好了，望采纳，谢谢！😋

**Comment by 3508454055** [comment]
欢迎进QQ辅助群交流：323175670
