### ISSUE TITLE
小白求助

### ISSUE THREAD

**Issue by ShmilyChen** [pansong291/XQuickEnergy#63]
请问一下，大佬是是用的那个版本的JDK和Android SDK以及gradle呀，安卓小白想尝试一下自己编译

**Comment by pansong291** [comment]
android sdk 28，xposed api 54

**Comment by ShmilyChen** [comment]
java版本呢
我使用jdk8
`for(Map.Entry entry: idSet)`报错
`java: 不兼容的类型: java.lang.Object无法转换为java.util.Map.Entry`

**Comment by pansong291** [comment]
> java版本呢
> 我使用jdk8
> `for(Map.Entry entry: idSet)`报错
> `java: 不兼容的类型: java.lang.Object无法转换为java.util.Map.Entry`

你自己强转一下类型吧

**Comment by 3508454055** [comment]
欢迎进QQ辅助群交流：323175670
