### ISSUE TITLE
正式版1.2.7支付宝闪退

### ISSUE THREAD

**Issue by Rakau** [pansong291/XQuickEnergy#67]
[或许你遇到的问题已经在 wiki 里有说明了](https://github.com/pansong291/XQuickEnergy/wiki)  

[请先阅读此反馈 BUG 的注意事项，再提交](https://github.com/pansong291/XQuickEnergy/issues/25)

1.2.6没问题,到了1.2.7就出问题了支付宝版本:10.1.75 GP版
打开支付宝后等十秒左右就闪退了,前台和后台都是一样...日志没有找到闪退的条目 MIUI11安卓10

**Comment by Rakau** [comment]
另外 千牛也闪退了

**Comment by Rakau** [comment]
清除全部的XQuickEnergy数据后恢复正常

**Comment by 3508454055** [comment]
欢迎进QQ辅助群交流：323175670
