### ISSUE TITLE
最新版支付宝10.17.5bug

### ISSUE THREAD

**Issue by wzgrx** [pansong291/XQuickEnergy#68]
打开运动会弹
![Screenshot_2019-10-16-16-55-21-895_com eg android AlipayGphone](https://user-images.githubusercontent.com/39661556/66904218-49e2a080-f036-11e9-8b14-2ca3159118ee.jpg)
打开口碑点任意图标回会弹
![Screenshot_2019-10-16-16-56-51-824_com lbe security miui](https://user-images.githubusercontent.com/39661556/66904267-5e269d80-f036-11e9-9eef-ab69eccfc409.jpg)
换回68版支付宝正常，没有弹窗
手机小米
miui10
安卓9
需要日志可以发邮箱
是我一个人的问题吗

**Comment by jzx765** [comment]
特意试了一下，没有这个问题，米9，MIUI11，安卓10，75支付宝

**Comment by a2212997715** [comment]
换个版本的支付宝就不会，很奇怪，

**Comment by a2212997715** [comment]
取消激活xq模块就不会弹窗，激活就会，确定就是xq的问题。。

**Comment by a2212997715** [comment]
没有用啊，卸载重装了很多次，还是会弹

**Comment by jzx765** [comment]
那确实不知道这个问题了，酷安好多人在用，如果有这样的问题，应该早炸了，而且测试版也一直在发，都没有人反馈这个，要不你再找个人测一下

**Comment by a2212997715** [comment]
算了，其实也不影响，面前差不多完美了

**Comment by 3508454055** [comment]
欢迎进QQ辅助群交流：323175670
