### ISSUE TITLE
miui11太极里无法兼容吗

### ISSUE THREAD

**Issue by 168308711q** [pansong291/XQuickEnergy#69]
[或许你遇到的问题已经在 wiki 里有说明了](https://github.com/pansong291/XQuickEnergy/wiki)  

[请先阅读此反馈 BUG 的注意事项，再提交](https://github.com/pansong291/XQuickEnergy/issues/25)

**Comment by 168308711q** [comment]
XQuickEnergy1.2.7（已汉化来自酷安）已经用上了，安卓10配合最新版支付宝正常使用；无极需要作者的序列码，但太极阳白名单里也支持较新的模块呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Rakau"<notifications@github.com&gt;; 
发送时间: 2019年10月17日(星期四) 下午5:02
收件人: "pansong291/XQuickEnergy"<XQuickEnergy@noreply.github.com&gt;; 
抄送: "ャ﹎ 相伴、"<168308711@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [pansong291/XQuickEnergy] miui11太极里无法兼容吗 (#69)




太极里,如果你没有无极的使用权限,那么请用edxposed。没有无极的太极是阉割版

**Comment by 3508454055** [comment]
欢迎进QQ辅助群交流：323175670
