### ISSUE TITLE
蚂蚁庄园功能建议

### ISSUE THREAD

**Issue by dozen007** [pansong291/XQuickEnergy#7]
希望可以加入星星球小游戏的自动化，这里有一份auto.js代码，不知道有没有用

auto();

const WIDTH = Math.min(device.width, device.height);
const HEIGHT = Math.max(device.width, device.height);

start();
function start() {
var timeout = 10000;
// 截图权限申请
threads.start(function () {
var remember;
var beginBtn;
if (remember = id("com.android.systemui:id/remember").checkable(true).findOne(timeout)) {
remember.click();
}
if (beginBtn = classNameContains("Button").textContains("立即开始").findOne(timeout)) {
beginBtn.click();
}
});
if (!requestScreenCapture(false)) {
toastLog("请求截图失败");
exit();
}

toastLog("请打开星星球界面");
launchApp("支付宝");
waitForActivity("com.alipay.mobile.nebulacore.ui.H5Activity");
//sleep(5000);

var antManor = new AntManor();

antManor.play();

exit();
}

function AntManor() {
this.colors = ["#FF4C4C", "#4E86FF"];
this.find_time = 5000;

this.play = function () {
var len = this.colors.length;
var wait_time = 100;
var baseline = device.height * 0.412 | 0;
var min_height = baseline * 0.55 | 0;

// 发球
var point = this.findColorPoint(len);
var x = point.x;

**Comment by pansong291** [comment]
难搞，建议使用Auto.js运行
