### ISSUE TITLE
xxmin后可收能量的提示大概率不提示

### ISSUE THREAD

**Issue by 168308711q** [pansong291/XQuickEnergy#75]
支付宝里有很多好友名后提示多少分钟后能收，但是XQU上没有生效；若是等早高峰定时检测其实已经晚了，大部分已被收取，除非把检测间隔设为很小很小

**Comment by zkzqzzz** [comment]
1.2.7确实有问题，我回退1.2.6就好了

**Comment by Rakau** [comment]
看看日志runtime是不是登陆200超时了

**Comment by 168308711q** [comment]
请问日志在哪里查看呢

**Comment by 3508454055** [comment]
欢迎进QQ辅助群交流：323175670
