### ISSUE TITLE
MIUI11安卓10貌似对XQ完全不适配

### ISSUE THREAD

**Issue by 5206yhn7ygv** [pansong291/XQuickEnergy#80]
我下了1.25-1.27三个版本，没有一个有用，没有一个生效，希望作者让XQ完美适配安卓10，如果适配了的话，我会捐赠打赏的。

**Comment by 168308711q** [comment]
我们的都能用啊

**Comment by ATIAboo** [comment]
该捐就捐，不要说的好像你的捐赠打赏是赏赐一样。

**Comment by 5206yhn7ygv** [comment]
> 我下了1.25-1.27三个版本，没有一个有用，没有一个生效，希望作者让XQ完美适配安卓10，如果适配了的话，我会捐赠打赏的。

**Comment by 5206yhn7ygv** [comment]
> 该捐就捐，不要说的好像你的捐赠打赏是赏赐一样。



> 该捐就捐，不要说的好像你的捐赠打赏是赏赐一样。

我想怎么表达就怎么表达

**Comment by 3508454055** [comment]
欢迎进QQ辅助群交流：323175670
