### ISSUE TITLE
2019-11-28 15:52:24  定时检测开始 2019-11-28 15:52:24  系统繁忙，请稍后重试

### ISSUE THREAD

**Issue by 168308711q** [pansong291/XQuickEnergy#88]
如图时间开始无法收取自己能量，其余正常...
应该是大面积这样吧

**Comment by ww870854** [comment]
从日志看，是无法读取自己的ID。

**Comment by LouisFan1998** [comment]
对对对，我的也是这样。今天（29号）开始，可以收取别人的能量自己的没办法收

**Comment by 168308711q** [comment]
没组织啊，从酷安来看确实大面积失效且小鸡也出问题了

**Comment by klgd** [comment]
我的也是自己的收不了，收别人的可以，小鸡好像是正常的

**Comment by 2318414890** [comment]
我的也是，收不了自己的，小鸡也不自动养了

**Comment by sun3596209** [comment]
特地登录，就是为了反馈这个问题，看来不是我一个人。

**Comment by Zhangyuxiang97** [comment]
开源的，有没有大佬顶替修复一下

**Comment by swh922** [comment]
集体翻车了，不能收自己能量，不能浇水，庄园失效，期待大佬修复

**Comment by zphjl** [comment]
有人测试旧版本的支付宝会这样吗？我也是今天庄园全失效，森林不收自己

**Comment by 3508454055** [comment]
欢迎进QQ辅助群交流：323175670
